name: GitHub Action Test Demo
on:
  pull_request:
    types: [assigned]
    braches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 设置环境
      - name: Checkout
        uses: actions/checkout@v2
      - name: setNode
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # build
      - name: yarn install, build
        run: |
          yarn install
          yarn build
# test
